import { button } from "@/styles";
import { ClerkProvider, SignInButton, UserButton, auth } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const font = Cabin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${font.className} bg-slate-900`}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}

function Navbar() {
  const { userId } = auth();
  return (
    <nav className="w-full border-b border-slate-800 px-6 py-4 flex items-center">
      <Link href="/" className="text-emerald-400 font-medium text-xl">
        Jot
      </Link>
      <div className="mx-auto h-12" />
      {userId ? (
        <UserButton afterSignOutUrl="/" />
      ) : (
        <SignInButton>
          <button className={button()}>Sign In</button>
        </SignInButton>
      )}
    </nav>
  );
}
